apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mini-node-exporter
  namespace: foo
  labels:
    app: mini-node-exporter
spec:
  selector:
    matchLabels:
      app: mini-node-exporter
  template:
    metadata:
      labels:
        app: mini-node-exporter
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '23333'
    spec:
      containers:
      - name: mini-node-exporter
        image: prayagsavsani/mini-node-exporter:latest
        ports:
        - protocol: TCP
          containerPort: 23333
---
apiVersion: v1
kind: Service
metadata:
  name: mini-node-exporter
  labels:
    app: mini-node-exporter
    service: mini-node-exporter
spec:
  type: NodePort
  selector:
    app: mini-node-exporter
  ports:
  - port: 23333
    targetPort: 23333
    nodePort: 30000
---
