---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: foo
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - protocol: TCP
          containerPort: 3000
        volumeMounts:
          - name: grafana-datasource-volume
            mountPath: /etc/grafana/provisioning/datasources/
          - name: grafana-dashboard-volume
            mountPath: /etc/grafana/provisioning/dashboards/
      volumes:
        - name: grafana-datasource-volume
          configMap:
            name: grafana-datasource
        - name: grafana-dashboard-volume
          configMap:
            name: grafana-dashboard
            items:
            - key: dashboard.yaml
              path: dashboard.yaml
            - key: mini-node-exporter-dashboard.json
              path: mini-node-exporter-dashboard.json
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
    service: grafana
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30002
---
